version: '3'

services:
  wrong-notebook:
    # 使用本地构建的镜像
    build: .
    image: wrong-notebook:latest
    container_name: wrong-notebook
    restart: always
    ports:
      - "3000:3000"
    environment:
      # NEXTAUTH_URL 根据实际情况设置你的信息
      #- NEXTAUTH_URL=http://your_domain_name:3000
      # - NEXTAUTH_SECRET= 根据实际情况设置你的信息
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
      - ./config:/app/config

